use DEMO

select * from emp;

SELECT CITY,  COUNT(EID) AS ' NO OF EMP' FROM EMP 
GROUP BY CITY 
ORDER BY COUNT(EID);

----------------
SELECT * FROM EMP 
WHERE EMAIL NOT LIKE '%YAHOO%';

-----------------------------------
SELECT DESI,COUNT(EID) AS 'NO OF EMP', SUM(SALARY) AS 'TS' FROM EMP_SAL
GROUP BY DESI
ORDER BY SUM(SALARY) DESC;